version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /infrastructure/application-load-balancer
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /pygoat
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /pygoat
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
