name: Example workflow for Python using Snyk - CODE test with GH integration
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.7@cdb760004ba9ea4d525f2e043745dfe85bb9077e # master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Build, tag, and push docker image to Amazon ECR
        run: 
          snyk code test --sarif-file-codesarif.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@231aa2c8a89117b126725a0e11897209b7118144 # v1.1.39
        with:
          sarif_file: snyk.sarif
      - name: uppload code sarif
        uses: github/codeql-action/upload-sarif@231aa2c8a89117b126725a0e11897209b7118144 # v1.1.39
        with:
          sarif_file: codesarif.sarif
