name: SCA Check - GH Actions 
on: push
permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: checkout code
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
        
      - name: mkdir for uploaded artifacts
        run: mkdir downloads 
        
      - name: install/auth to Snyk 
        run: 
          npm install snyk -g 
          npm install snyk-to-html -g
          
      - name: run Snyk
        run: snyk test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
